import styles from "./TrendingPage.module.scss";
import Head from "next/head";
import { Textarea, TextInput } from "@mantine/core";
import { api } from "../../utils/api";
import { PostList } from "../../components/PostList/PostList";

export default function SettingsPage() {
  const { data: trendingData } = api.post.getTrending.useQuery({ page: 0 });

  if (!trendingData) {
    return <></>;
  }

  return (
    <>
      <Head>
        <title>Grumbler | Settings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.trendingsPage}>
        <PostList posts={trendingData.posts} />
      </div>
    </>
  );
}
