import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "../utils/api";
import { useEffect } from "react";
import { Sidebar } from "../components/Sidebar/Sidebar";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Grumbler</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet minus
        nesciunt suscipit reprehenderit incidunt ducimus delectus obcaecati est
        rerum officia nihil provident vero corrupti, veritatis cupiditate.
        Possimus, laborum vitae. Lorem ipsum dolor sit, amet consectetur
        adipisicing elit. In amet minus nesciunt suscipit reprehenderit incidunt
        ducimus delectus obcaecati est rerum officia nihil provident vero
        corrupti, veritatis cupiditate. Possimus, laborum vitae. Lorem ipsum
        dolor sit, amet consectetur adipisicing elit. In amet minus nesciunt
        suscipit reprehenderit incidunt ducimus delectus obcaecati est rerum
        officia nihil provident vero corrupti, veritatis cupiditate. Possimus,
        laborum vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit.
        In amet minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae. Lorem ipsum dolor sit, amet
        consectetur adipisicing elit. In amet minus nesciunt suscipit
        reprehenderit incidunt ducimus delectus obcaecati est rerum officia
        nihil provident vero corrupti, veritatis cupiditate. Possimus, laborum
        vitae. Lorem ipsum dolor sit, amet consectetur adipisicing elit. In amet
        minus nesciunt suscipit reprehenderit incidunt ducimus delectus
        obcaecati est rerum officia nihil provident vero corrupti, veritatis
        cupiditate. Possimus, laborum vitae.
      </div>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  return (
    <div className={styles.authContainer}>
      <p className={styles.showcaseText}>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
      </p>
      <button
        className={styles.loginButton}
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
