import styles from "./UserPage.module.scss";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { api } from "../../utils/api";
import { PostList } from "../../components/PostList/PostList";
import { UserHeader } from "../../components/UserHeader/UserHeader";

interface UserPagePropsType {
  username: string;
}

export default function UserPage({ username }: UserPagePropsType) {
  const { data: userData, refetch } = api.user.getUser.useQuery({
    page: 0,
    username,
  });

  const followMutation = api.user.follow.useMutation();
  const unfollowMutation = api.user.unfollow.useMutation();

  if (!userData) {
    return <></>;
  }

  return (
    <>
      <Head>
        <title>Grumbler</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.userPage}>
        <UserHeader
          {...userData.user}
          onFollowClick={() => {
            if (userData.user.isUserFollowing) {
              unfollowMutation.mutate({ username });
            } else {
              followMutation.mutate({ username });
            }

            refetch();
          }}
        />
        <PostList posts={userData.posts} />
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => ({
  props: {
    username: query.username,
  },
});
